export default {
    EN: {
        hello: 'Hello',
        skills: 'Skills',
        education: 'Education',
        portfolio: 'Portfolio',
        contact: 'Contact Me',
        title: 'I am Bohdana Stetsenko',
        subtitle: 'I am a future Frontend Developer. I am a hardworking, punctual and responsible person. I am looking for a company where I will be able to develop and improve my professional knowledge.',
        phone: 'Phone',
        email: 'Email',
        social: 'Socail',
        skillsParagraph: 'I am inspired by creating great work with people who are as passionate as I am about building something awesome.',
        skillsFirstTitle: 'Frontend Development',
        skillsFirstTitleParagraph: 'Fluent knowledge of JavaScript, HTML, CSS, SASS/SCSS; Git; adaptive and responsive layout',
        skillsSecondTitle: 'Other',
        skillsSecondTitleParagraph: 'Intermediate level of English, experience working in a team environment, good eye for quality design and aesthetics',
        educationParagraph: 'All my life I have been driven by my strong belief that education is important. I try to learn something new every single day. Despite if it is about computer science or it is something else.',
        educationLyceum: 'Ukrainian Physical and Mathematical Lyceum by Shevchenko',
        educationShevchenko: 'KNU by Shevchenko, faculty: Computer Science',
        educationCourse: 'Frontend Developer Course in prog.kiev.ua',
        year: 'since 2019',
        educationGrinchenko: 'Borys Grinchenko Kyiv University, faculty: English Philology',
        allProjects: 'All projects',
        webSites: 'Web sites',
        goToGitHub: 'Go to GitHub',
        projectTitle1: 'Slider Four Seasons',
        projectTitle2: 'Slider Animals',
        projectTitle3: 'The Game Aim Training',
        projectTitle4: 'Web Site Empower Your Business',
        projectTitle5: 'Web Site Your Personalized Coffee',
        projectTitle6: 'Web Site Cleaning',
        contactPargraph: 'Are you working on something great? I would love to help make it happen! Drop me a letter!'
    },
    UA: {
        hello: 'Про мене',
        skills: 'Навички',
        education: 'Освіта',
        portfolio: 'Портфоліо',
        contact: 'Мої контакти',
        title: 'Я - Богдана Стеценко',
        subtitle: 'Я майбутній Frontend розробник. Я працьовита, пунктуальна і відповідальна людина. Я шукаю компанію, де зможу розвивати та вдосконалювати свої професійні знання.',
        phone: 'Телефон',
        email: 'Електронна пошта',
        social: 'Соціальні мережі',
        skillsParagraph: 'Мене надихає створення чогось надзвичайного, і особливо роблячи це з людьми, які так само пристрасно, як і я, будують щось чудове.',
        skillsFirstTitle: 'Frontend розвиток',
        skillsFirstTitleParagraph: 'Вільне володіння JavaScript, HTML, CSS, SASS/SCSS; Git; адаптивна і кроссбраузерна верстка',
        skillsSecondTitle: 'Інше',
        skillsSecondTitleParagraph: 'Рівень англійської мови: Intermediate, досвід роботи в команді, хороший погляд на якісний дизайн та естетику',
        educationParagraph: 'Усе своє життя я керувалася твердою впевненістю, що освіта важлива. Я намагаюся щодня дізнаватися щось нове. Незважаючи на те, чи мова йде про інформатику чи про щось інше.',
        educationLyceum: 'Український фізико-математичний ліцей ім. Т. Шевченка',
        educationShevchenko: "КНУ ім. Т. Шевченка, факультет: комп'ютерні науки",
        educationCourse: 'Курс Frontend Developer у prog.kiev.ua',
        year: 'з 2019',
        educationGrinchenko: 'Національний університет ім. Б. Грінченка, факультет: англійська філологія',
        allProjects: 'Усі проєкти',
        webSites: 'Вебсайти',
        goToGitHub: 'Перейти до GitHub',
        projectTitle1: 'Слайдер Four Seasons',
        projectTitle2: 'Слайдер Animals',
        projectTitle3: 'Гра Aim Training',
        projectTitle4: 'Вебсайт Empower Your Business',
        projectTitle5: 'Вебсайт Your Personalized Coffee',
        projectTitle6: 'Вебсайт Cleaning',
        contactPargraph: 'Ви працюєте над чимось крутим? Я хотіла б допомогти, щоб це здійснилося! Напишіть мені!'
    }
}

